repos:
  - repo: local
    hooks:
      - id: run-syntax-check
        name: "PHP Syntax Check"
        entry: bash -c 'find ./tests -name '*.php' -print0 | xargs -0 -n1 php -l'
        language: system
        stages: [pre-push]
