repos:
  - repo: local
    hooks:
      - id: run-syntax-fixer
        name: "PHP Syntax Check"
        entry: bash -c 'find ./app -name '*.php' -print0 | xargs -0 -n1 php -l'
        language: system
        stages: [pre-push]
      - id: test-pre-commit
        name: "Pre Commit Example"
        entry: bash -c 'echo "hello pre-commit"'
        language: system
        stages: [pre-commit]
