openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/products:
    get:
      summary: '產品列表 包括搜尋功能'
      operationId: ''
      description: ''
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  name: Apple
                  price: 100
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: Apple
                  price:
                    type: integer
                    example: 100
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 產品名稱.
                  example: Apple
                minPrice:
                  type: number
                  description: 最低價格.
                  example: 1.0
                maxPrice:
                  type: number
                  description: 最高價格.
                  example: 1000.0
      security: []
    post:
      summary: 新增產品
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 限制100字元
                  example: quia
                price:
                  type: integer
                  description: 限制1以上
                  example: 14
      security: []
  '/api/products/{id}':
    get:
      summary: 產品詳細資訊
      operationId: ''
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Endpoints
      security: []
    put:
      summary: 更新產品資訊
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 限制100字元
                  example: velit
                price:
                  type: integer
                  description: 限制1以上
                  example: 11
      security: []
    delete:
      summary: 刪除產品
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: molestiae
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
